[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
log = "0.4.22"
regex = "1.11.1"
simple_logger = "5.0.0"
itertools = "0.13.0"
ndarray = "0.16.1"